# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 236)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.roast_edit = QtWidgets.QLineEdit(Form)
        self.roast_edit.setObjectName("roast_edit")
        self.gridLayout.addWidget(self.roast_edit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.flavor_edit = QtWidgets.QLineEdit(Form)
        self.flavor_edit.setObjectName("flavor_edit")
        self.gridLayout.addWidget(self.flavor_edit, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.price_edit = QtWidgets.QDoubleSpinBox(Form)
        self.price_edit.setObjectName("price_edit")
        self.gridLayout.addWidget(self.price_edit, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.volume_edit = QtWidgets.QDoubleSpinBox(Form)
        self.volume_edit.setObjectName("volume_edit")
        self.gridLayout.addWidget(self.volume_edit, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.type_edit = QtWidgets.QComboBox(Form)
        self.type_edit.setObjectName("type_edit")
        self.gridLayout.addWidget(self.type_edit, 4, 2, 1, 1)
        self.save_button = QtWidgets.QPushButton(Form)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 5, 1, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактировать"))
        self.label.setText(_translate("Form", "Прожарка"))
        self.label_2.setText(_translate("Form", "Вкус"))
        self.label_3.setText(_translate("Form", "Цена"))
        self.label_4.setText(_translate("Form", "Объем упаковки"))
        self.label_5.setText(_translate("Form", "Тип"))
        self.save_button.setText(_translate("Form", "Сохранить"))
